### ISSUE TITLE
debugging and maintenance of user code

### ISSUE THREAD

**Issue by jreiser** [fyngyrz/aa_macro#6] opened 2017-11-25 14:25 UTC
The single most important facility in any macro language is some provision for debugging user output.  Given a location in the output, such as byte position in the file (or line number and character number), give a traceback of how that character was generated.  What macros, arguments, and conditionals were responsible?  This is supremely important for maintenance.  For instance, a large software project often has a suite of Makefiles.  A new maintainer of the project discovers that a particular command-line invocation of <tt>make</tt> invokes the wrong command on the 42nd sub-invocation of the shell.  Which of the hundreds of implicit rules, explicit rules, internal variable assignments, inherited environment variables, #included files, etc., are responsible?  Where is the bug?

Currently <tt>make</tt> offers no help.  Something better would be a symbol history.  For every assignment to a named object (internal variable, environment variable, rule) record a 64-bit word containing 32 bits of sequence number, 12 bits of "filenumber" and 20 bits of "line number".  Provide searchable access to this history.  Then the new maintainer can trace backwards and figure out the culprits.

**Comment by fyngyrz** [comment] 2017-11-25 18:21
Great input. I agree, debugging info is very useful. aa_macro provides several different kinds.

If you make a built-in syntax error that can be detected, aa_macro presently inserts the error into the output stream in plaintext in a (hopefully) obvious way.

If you fail to close a brace, aa_macro dumps the previous command (the unclosed one) into the output stream. It doesn't dump the line number, but I can make it do so easily enough... however, as aa_macro isn't a line-oriented language, that may not be as diagnostic as one might imagine. Still can't hurt, and won't slow things down significantly, so I'll do it.

One good thing is that aa_macro isn't nearly as quirky as make is, so typically errors are easily comprehended.

One bad thing is that bracing errors are _very_ difficult to localize by the processing code, because it doesn't know what you're doing until you're done doing it, and if you leave off a closing brace, you were never done. Or IOW, a command might take a little following content, or a lot.

[edit:] Okay, I've added line numbers to the error detection:

![error-output](https://user-images.githubusercontent.com/11237323/33233597-b78d0520-d1d5-11e7-8d02-fea0ecf91fa0.png)

That test page, btw, is [located here.](http://ourtimelines.com/aamacropreview.html)

Finally, in my doc generation wrapper, [wtfm](https://github.com/fyngyrz/wtfm), there is a test area where you can drop code chunks and test them live independent of the rest of the document you are working on. This area, as shown in the image above, does syntax highlighting, tests for brace balance, and runs the code live (if it can.)

**Comment by jreiser** [comment] 2017-11-25 21:44
That's a nice beginning.  How about a "traceback" for each level of pending operation?  Line numbers <b>always</b> work for file or stream, but for arbitrary strings I suppose it's character count from the beginning of the definition of the macro, or from the start of recognition of the current parameter.

Then there are the decades-old ideas: Multiple character pairs that act as braces, either separately or nesting or interacting; "super parentheses" [LISP, 1960s] that force a match, terminating all un-terminated instances; etc.  If your bibliography doesn't go back to the String Handling Interpretive Translator [MIT, 1960s; referenced in http://www.inwap.com/pdp10/hbaker/hakmem/Figure3b.html] then you haven't looked far enough.

**Comment by fyngyrz** [comment] 2017-11-25 21:57
> How about a "traceback" for each level of pending operation?

Can you explain what you mean by this? I'm not following. My fault, I am certain. Agree that character position is pretty much the metric as far as being able to point specifically to something, when that's even possible.

> terminating all un-terminated instances; etc.

This is not practical in this case – termination is undefined when braces are missing, because nested termination occurs constantly and is syntactically no different than "proper" termination at the error level. There's nothing about the language that allows it to know what the authoring intent was, nor, I think, should there be. Braces do not define blocks in this language in a way that can be said to be an error until the entire stream has been processed – and at that point, the most I've been able to figure out to tell the user is the level that failed to close, which puts them one block away from the error (which could be quite a distance, in truth.)

It is entirely likely that the "correct" closing brace position might be tens or hundreds of kbytes away from the opening brace. Or 1. The parser can't evaluate where it should be.

I am certainly open to better error detection – would love it, in fact – but I'm just not seeing how it could be accomplished.

**Comment by jreiser** [comment] 2017-11-26 23:41
Here's a suggestion for "traceback".   A <i>position</i> is a triple (object_name, byte offset, character offset) where <i>object_name</i> designates a file, stream, macro definition body, macro formal parameter, or macro actual argument; and the offsets are from the beginning of the object.  When internal code reads and remembers the current position so that it can be restored later, then that is a Push of the current position onto a stack.  When internal code explicitly writes the current position from a position that was previously read and remembered, then that is a Pop of the stack.  (The current position is incremented implicitly by advancing to the next [adjacent] character within the same object, whether to generate output or to accumulate the definition of a macro body, formal parameter name, or actual argument value.)  Then a traceback is the contents of the stack of positions, with the current position being the implicit top-ot-stack.

The object_name for a macro or actual argument should contain a global sequence number as well as the user-specified name, and also it would be nice to record the current position at both the beginning and end of a definition.  The name of a macro formal parameter should contain the user-specified name, macro name, and formal parameter number.

**Comment by fyngyrz** [comment] 2017-11-27 02:33
Okay, that's pretty much what I thought you meant. Or, was afraid you meant. :)

Right now, when an error is actually detected, which is to say, the syntax of something is broken in a detectable way, the specifics of where and what when wrong are dumped out. Contextually. But this is very much a minority case; it's unworthy of a trace in the sense you mean it because where it is, is already dumped out.

Likewise, a typo in a built-in name that resolves to an unknown name is easily caught; same for an unknown user-defined style name, also usually a typo.

The real problem cases arise with depth of bracing. If, for instance, you miss a close brace on object A, then what happens is that the close brace on object B actually closes A, and C closes B, and D closes C, and so on until the text stream is exhausted. Then, and only then, can the parser determine that it's opened more braces than it closed; it doesn't (can't) know where it happened, it doesn't (can't) know why it happened, but it does keep a record of the last and the most previous (a two level trace, if you will) opening built-ins or user-defined invocations, and it dumps them out.

A trace as you describe, near as I can imagine it, would be very verbose, and would require very careful examination indeed to yield any benefit. I may be wrong on that point. I am willing to be told so.

I added the line number as you suggested, and I will add the character position (because as discussed earlier, lines aren't necessarily the entity at hand.) This is likely, but not certain, to hint at or precisely locate some types of problems, specifically those that are descendant from the outmost recent context – typically the object prior to A is dumped.

That's if there was one error. If more than one... well, it'll take more than one build and subsequent error report to catch those.

I don't see that there's much benefit to showing what objects got defined where, inasmuch as they will indeed get defined, if not as intended. I may be guilty of insufficient vision here and if so, I hope you can clear things up a bit for me. Also, there's a distinct downside: right now, the build process is extremely fast, or at least, I consider it so keeping mind what gets done. The only way I can think of to do what you're suggesting without inherent severe damage to the build speed – other merits aside – is to create a second parser that builds with these amenities when some debug flag is on so that the "normal" parser isn't inpacted. That's going to slow things down. A lot. Off the cuff, (handwaving, admittedly) I think it would be half as fast, or worse. That's sorta scary.

The largest document I have written \([this one](http://ourtimelines.com/widoc/tocpage.html)\), takes about 30 seconds to build. That's presently over 400 output pages. 60 seconds would be so, so painful. It might be worse.

Inasmuch as I am having trouble imagining the benefit, and cannot actually describe _why,_ I will accept a "look, this will really help, just do it" answer and blindly "just do it"; but I'd like a more wordy one, if you can spare the time. If you think I can only understand by seeing the result, say that too, please. :)

\[Edit:\] I should also mention there are several builds in a documentation system. The first builds a global project context. So that needs a trace. Then, there is a global style context. That needs a trace. Then, for every page, there is a local context, and then a page context. Both need a trace.

The global project and global style contexts are each fully independent builds. Errors in them will not cascade into each other or into the local or page contexts.

Errors in the local context will also not cascade into the page context (by all of this, I mean that _bracing level_ errors will not so cascade... other effects are quite possible, but may not be detectable.)

Each of these builds needs a  trace. For instance, for the document above, there are two global builds, and 800+ local/page builds. That's 800+ separate traces. The local and page contexts can be placed at the bottom of the generated pages, I'd have to find a place to put the global ones. Perhaps on the first page \(they're complete before the first page is generated.\)

Just as an FYI.

**Comment by jreiser** [comment] 2017-11-27 18:46
[This reply is somewhat disconnected, but is mostly in order.]

> it's unworthy of a trace in the sense you mean it because where it is, is already dumped out.

That kind of error, where the context is all or mostly in top-level literal input, is easy to find and fix.  When the error arises due to juxtaposition of deeply-nested styles operating on generated strings, then a traceback really helps, particularly when subsets of styles are just minor variations of each other.

> The real problem cases arise with depth of bracing. If, for instance, you miss a close brace on object A, then what happens is that the close brace on object B actually closes A, ..., and so on until the text stream is exhausted.

There should be an option to declare something like, "Any invocation of this macro (or actual argument that corresponds to parameter #k) may not consume more than 4000 bytes of [top-level ?] input." Also, "un-escaped linefeeds (or two consecutive linefeeds, or a blank line [two linefeeds with only whitespace in between]) are not allowed."  These are like user-chosen safety belts.

> I added the line number as you suggested, ...

Thank you!

> [keeping tracebacks] That's going to slow things down. A lot.

Yes, it will be slower at the lowest level and for global rebuilds. Re-generating <b>Ulysses</b> (James Joyce) will take 7 minutes instead of 5.  But without good debugging aids then finding and fixing an intricate bug can take a whole day or more of frustrating work.  Initial composing is tough; but editing and revising takes more time overall, particularly when the original author is no longer available.

One thing to think about is using a separate thread to generate and save the traceback information. Write the stream to a file (compress on-the-fly using zlib or LZO, with synchronization points), and process the file later (on demand, which usually will be never, or only the most-recent page, etc..)  The first implementation might even do this using a pipe to a separate process.

> Each of these builds needs a trace.

That's right.  This is an "Interactive Development Environment (IDE)" for the document suite, where partial builds are recorded, and dependencies are tracked and managed.

> For instance, for the document above, there are two global builds, and 800+ local/page builds.

That's good to hear.  Like the page-independence policy and other Document Structuring Conventions for PDF ("Print pages 3 through 5, and 8"), where PDF itself is an adaptation of PostScript for usability  and manageability and safety.

[New topics; but possibly related? Stuff to think about, not necessarily to implement (at least not right away.)]:

Right-to-left languages: Hebrew, Arabic, ...

Synchronized columns: Corresponding paragraphs and list items have the same vertical offset.  Like an implicit table, but the source is "un-interleaved".  Also consider the properties of the musical score for a piano duet (1 piano, 4 hands): the <i>primo</i> part is on the right-hand page, the <i>secundo</i> part is on the facing left-hand page, and the systems of staffs are synchronized.  Also, the conductor's score for a symphony.  [Even the script of a stage play, or an interactive SMS text chat, is related.]

Auditing: Does every literal word of top-level input appear in the output? And no more than N times (once in each of: text, index, table of contents, list of figures, ...)?

**Comment by fyngyrz** [comment] 2017-11-27 20:41
> There should be an option to declare something like, "Any invocation of this macro (or actual argument that corresponds to parameter #k) may not consume more than 4000 bytes of [top-level ?] input." 

...and suppose this happens. Then what? At that point, the code is broken anyway – how are you better off?

> Synchronized columns: Corresponding paragraphs and list items have the same vertical offset. Like an implicit table, but the source is "un-interleaved". 

This is easily done in many ways. How you would go about it would differ depending on the output style you wanted to use; but offhand, HTML, markdown, and plaintext would all be very easy - in fact, multiple encoding competent styles that took a parameter of how you wanted the output coded would be no problem. For text, there are various padding and centering options. For markup languages, typically they'll have something of their own you can leverage. Of course you can use CSS or tables, or both, if you're aiming at an HTML environment.

> Does every literal word of top-level input appear in the output? 

In the context of a page, yes.

In the context of the global project, the global styles, and the local styles, no – only persistent items such as global variables and global styles are meaningful at the global level, and only persistent items of both global and local natures are meaningful at the local level.

On the page, though, normal text is... normal text. You do have to escape [] and {} if you want to use them, though. Or you can use a built-in to take care of that for you.

> And no more than N times (once in each of: text, index, table of contents, list of figures, ...)?

The canned index, toc, etc that I supply are fairly simplistic; so you make an entry in one of those, you get a unique entry for that... but they can be made to flex in any way you like. Generally speaking, they're just styles, and you can do with them whatever you please. If you need help at any point for something specific, just ask. I _like_ messing with it. :)

**Comment by jreiser** [comment] 2017-11-27 20:56
> [limited forward scanning] ...and suppose this happens. Then what? At that point, the code is broken anyway – how are you better off?

You can use binary search, plus your knowledge of the intended mapping from input to output, to help you localize and understand the error.

**Comment by fyngyrz** [comment] 2017-11-27 22:06
Well, no, not generally. Here's what happens: If there's too few closing braces, generation doesn't complete, because the highest level brace doesn't close – and that's usually an operator that wraps everything else, so... you get nothing. So what you _do_ get is an error message along with the last known level trace. If there's too many closing braces, generation completes early – and you (well, I) can almost always tell where it happened, because things go missing from then on.

When I say "its broken anyway", I mean _really_ broken. Generation goes so far into the bad that it's not anything you can can really search, per se.

I've thought about this a lot, and come up empty on decent diagnosis... that's why all the questions about the stack trace stuff.

**Comment by jreiser** [comment] 2017-11-27 22:13
Alright, I will use <tt>/usr/bin/split --bytes=</tt><i>N</i> &nbsp; to truncate the input, and do binary search on that.  You're right, this is <i>really</i> broken.

**Comment by fyngyrz** [comment] 2017-11-27 22:20
Just got the character index in the error messages. Progress. :)

**Comment by fyngyrz** [comment] 2017-11-27 22:22
Are you using the class by itself, or the doc system wrapper?

**Comment by fyngyrz** [comment] 2017-11-27 22:25
You can try various things a bit at a time [here](http://ourtimelines.com/aamacropreview.html) – I keep it right up to date with the latest code.

Just copy, paste, and test.

**Comment by fyngyrz** [comment] 2017-11-27 23:26
okay, I've added a basic trace to the project. Invoke like this:

`mod = macro(debug=True)`

then, after you've run your generate, you can get the results as text here:

`results = mod.getdebug()`

...I pretty much just winged it on the formatting. Totally open to suggestions.

**Comment by fyngyrz** [comment] 2017-11-28 00:05
mmm, okay, redid that so that the debug info is stored as a tuple (as you suggested, more or less.) Much more flexible for future futzing around with.

**Comment by jreiser** [comment] 2017-11-28 17:24
Here are 3 heuristics.

1) When scanning for a closing brace, then remember the position of the first 50 and most-recent 50 braces of any kind.  Dump those lists (with matches identified) as part of the error message when matching fails.  Perhaps 50 is not the right number, but 20 is definitely too small; that is only ten pairs.  30 to 35 might be enough in most cases.

2) Rank different strengths of braces: say () weakest, [] intermediate, {} strongest.  A closing brace closes not only its own match, but also any unmatched weaker braces in the span back to its own match.

3) Use control-Z (decimal 26, octal 032, hex 0x1A) as "kryptonite".  it closes all open braces to its left (if any).  Also, it is considered to be an alphabetic character, so it gets carried along and will close all open braces to its left (if any) whenever it appears in an expansion that gets re-scanned.  Control-Z is the DOS End-Of-File on the console, like Control-D on a Linux TTY.

**Comment by fyngyrz** [comment] 2017-11-28 18:02
Those are interesting notions, and I will consider them.

Here's where I'm at now (within the doc system) in displaying a trace of what's going on; this is a simple page with a TOC heading on it, and a few paragraphs with some various stylings in them. This might give you an idea of just how flaming busy things are "under the hood", perhaps inspire some further insights:

![debuginfo](https://user-images.githubusercontent.com/11237323/33335858-82da646e-d42b-11e7-84af-383c51eab8f7.png)

**Comment by fyngyrz** [comment] 2017-11-28 20:06
More betterized:

![parse2](https://user-images.githubusercontent.com/11237323/33341675-e867d5b2-d43c-11e7-8ccf-7223f489e50b.png)

**Comment by fyngyrz** [comment] 2017-11-29 13:47
Okay, one more bit... the truncated information for the built-ins and styles was chafing me, so I built CSS tooltips that will display all the content:

![hovertip](https://user-images.githubusercontent.com/11237323/33378147-2660c68c-d4d1-11e7-8cd7-0f9151fbdbab.png)

This way, the nesting and dependence remains clean and obvious (well, as obvious as possible) but you can still see the entire content of a built-in or a style.

I'm generating this content by parsing obj.devstack as [described here.](http://ourtimelines.com/aamacrodoc/appendixb.html)

**Closed as completed** 2019-08-04 20:23 UTC
